title:              Blogs by Subhangi
tagline:            on GitHub Pages
description:        blogs for ML/AI enthusiasts 
url:                http://subhu0028.github.io

author:
  name:             Subhangi
  url:              https://www.linkedin.com/in/subhangi-subhangi-18a7a2248/
  email:            subhangi1509@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
